---
driver:
    name: hyperv
    memory_startup_bytes: 2147483648
    dynamic_memory: true
    vm_switch: "'packer-hyperv-iso'"

provisioner:
  name: chef_zero
  roles_path: '../roles'

transport:
  name: winrm
  elevated: true
  password: 'vagrant'
  username: 'vagrant'

platforms:
  - name: win-server-2019-hyperv
    os_type: windows
    driver:
        parent_vhd_folder: '../../.output/hyperv/server_2019/Virtual Hard Disks'
        parent_vhd_name: 'server_2019.vhdx'
  - name: win-server-2019-vagrant
    driver:
      name: vagrant
      provider: hyperv
      box: server2019
      vm_hostname: false
      network:
        - ["public_network", bridge: "packer-hyperv-iso"]

verifier:
      name: inspec

suites:
  - name: common
    run_list:      
      #- recipe[chef-windows::install_build_prerequisites_packages]
      #- recipe[chef-windows::install_vs_2019]
      - role[chef-windows::quali_tc_agent]
    attributes:
        have_gui: 'false'
        box_settings:
            username: 'kitchen-username'
            user_password: 'kitchen-password'
            time_zone: 'kitchen-time_zone'
            locale: 'kitchen-locale'
            user_description: 'kitchen-user_description'