name 'chef-quali_teamcity'
maintainer 'Quali'
maintainer_email 'quali@quali.com'
license 'all_rights'
description 'Resources to automate Quali TeamCity agents'
long_description 'Resources to automate Quali TeamCity agents'
version '0.1.0'

depends 'qs_helper'
depends 'chef-windows'
depends 'chocolatey'