name "quali_tc_agent"
description "Quali TeamCity Agent"
run_list "recipe[qs_teamcity::set_timezone]",
		 "recipe[qs_teamcity::disable_firewall]",
		 "recipe[qs_teamcity::enable_samba_version_1]",
		 "recipe[qs_teamcity::set_computer_name]",
		 "recipe[qs_teamcity::join_domain]",
		 "recipe[qs_teamcity::add_domain_user_to_admin_group]",
		 "recipe[qs_teamcity::allow_rdp]",
		 "recipe[qs_teamcity::disable_uac]",
		 "recipe[qs_teamcity::set_power_plan]",
		 "recipe[qs_teamcity::enable_file_sharing]",
		 "recipe[qs_teamcity::enable_powershell_remoting]",
		 "recipe[qs_teamcity::set_env_vars]",
		 "recipe[qs_teamcity::install_agent_dependencies]",