---
driver:
    name: hyperv
    memory_startup_bytes: 2147483648
    dynamic_memory: true
    vm_switch: "'packer-hyperv-iso'"

provisioner:
  name: chef_zero
  roles_path: '../roles'

transport:
  name: winrm
  elevated: true
  password: 'vagrant'
  username: 'vagrant'

platforms:
  - name: win-10-hyperv
    os_type: windows
    driver:
        parent_vhd_folder: '../../packer/.output/hyperv/win10/Virtual Hard Disks'
        parent_vhd_name: 'win10.vhdx'
  - name: win-10-vagrant
    os_type: windows
    driver:
      name: vagrant
      provider: hyperv
      box: win10
      vm_hostname: false
      network:
        - ["public_network", bridge: "packer-hyperv-iso"]
  - name: win-server-core-2019-hyperv
    os_type: windows
    driver:
        parent_vhd_folder: '../../packer/.output/hyperv/server_core_2019/Virtual Hard Disks'
        parent_vhd_name: 'server_core_2019.vhdx'

verifier:
      name: inspec

suites:
  - name: common
    run_list:      
#      - recipe[chef-windows::install_ps_nuget_provider]
#      - recipe[chef-windows::allow_rdp]
#      - recipe[chef-windows::enable_file_sharing]
#      - recipe[chef-windows::set_local_account_token_filter_policy]
#      - recipe[chef-windows::add_sysprep_unattended]
#      - recipe[chef-windows::disable_cortana]
#      - recipe[chef-windows::uninstall_one_drive]
#      - recipe[chef-windows::uninstall_windows_media_player]
#      - recipe[chef-windows::clean_sxs]
      - role[windows_docker_server]
    attributes:
        have_gui: 'false'
        box_settings:
            username: 'kitchen-username'
            user_password: 'kitchen-password'
            time_zone: 'kitchen-time_zone'
            locale: 'kitchen-locale'
            user_description: 'kitchen-user_description'