name 'qs_packer_windows'
maintainer 'DG'
maintainer_email 'dg@dg.com'
license 'all_rights'
description 'Resources to automate windows configuration'
long_description 'Resources to automate windows configuration'
version '0.1.0'

depends 'qs_helper'
depends 'windows'
depends 'chocolatey'