name 'qs_packer_ubuntu'
maintainer 'DG'
maintainer_email 'dg@dg.com'
license 'all_rights'
description 'Resources to automate ubuntu configuration'
long_description 'Resources to automate ubuntu configuration'
version '0.1.0'

depends 'qs_helper'
depends 'openssh'