name 'chef-ubuntu'
maintainer 'DG'
maintainer_email 'dg@dg.com'
license 'all_rights'
description 'Resources to automate ubuntu configuration'
long_description 'Resources to automate ubuntu configuration'
version '0.1.0'

depends 'chef-helper'
depends 'openssh'